FROM debian:debian:bullseye-v1.4.1

COPY source.list /etc/apt/sources.list

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        tzdata && \
    rm -rf /var/lib/apt/lists/*

COPY newapi-edu-pure /newapi-edu-pure

EXPOSE 3000
WORKDIR /data
ENTRYPOINT ["/newapi-edu-pure"]
