apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: newapi
  labels:
    app.kubernetes.io/name: newapi-edu
    app.kubernetes.io/component: clickhouse
spec:
  type: ClusterIP
  ports:
    - name: native
      port: 9000
      targetPort: 9000
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: clickhouse
  namespace: newapi
  labels:
    app.kubernetes.io/name: newapi-edu
    app.kubernetes.io/component: clickhouse
subsets:
  - addresses:
      - ip: 172.16.74.1
    ports:
      - name: native
        port: 9000
        protocol: TCP
