apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: newapi
  labels:
    app.kubernetes.io/name: newapi-edu
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: postgres
  namespace: newapi
  labels:
    app.kubernetes.io/name: newapi-edu
    app.kubernetes.io/component: postgres
subsets:
  - addresses:
      - ip: 172.16.74.1
    ports:
      - name: postgresql
        port: 5432
        protocol: TCP
