apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: newapi
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - external-postgres.yaml
  - external-clickhouse.yaml
  - external-redis.yaml
  - external-ldap.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: newapi-edu-pure
    newTag: latest
