apiVersion: v1
kind: Secret
metadata:
  name: newapi-edu-secret
  namespace: newapi
  labels:
    app.kubernetes.io/name: newapi-edu
    app.kubernetes.io/component: backend
type: Opaque
stringData:
  SQL_DSN: postgresql://root:123456@postgres:5432/newapi?sslmode=disable
  LOG_SQL_DSN: clickhouse://default:@clickhouse:9000/newapi_audit
  REDIS_CONN_STRING: redis://:123456@redis:6379
  JWT_SECRET: mxjjCVN360MeoXaPHrFSMkuf524sXIG8Rg3fc5wsi7w=
