apiVersion: v1
kind: Service
metadata:
  name: newapi-edu
  namespace: newapi
  labels:
    app.kubernetes.io/name: newapi-edu
    app.kubernetes.io/component: backend
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: newapi-edu
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 3000
      targetPort: http
      nodePort: 30000
      protocol: TCP
